-- Disabled as the vanilla orbits are sufficient:
-- data.raw["planet"]["vulcanus"].orbit.sprite = {
-- 	type = "sprite",
-- 	filename = "__PlanetsLib__/graphics/orbits/orbit_vulcanus.png",
-- 	size = 640,
-- }
-- data.raw["planet"]["nauvis"].orbit.sprite = {
-- 	type = "sprite",
-- 	filename = "__PlanetsLib__/graphics/orbits/orbit_nauvis.png",
-- 	size = 960,
-- }
-- data.raw["planet"]["gleba"].orbit.sprite = {
-- 	type = "sprite",
-- 	filename = "__PlanetsLib__/graphics/orbits/orbit_gleba.png",
-- 	size = 1280,
-- }
-- data.raw["planet"]["fulgora"].orbit.sprite = {
-- 	type = "sprite",
-- 	filename = "__PlanetsLib__/graphics/orbits/orbit_fulgora.png",
-- 	size = 1600,
-- }
-- data.raw["planet"]["aquilo"].orbit.sprite = {
-- 	type = "sprite",
-- 	filename = "__PlanetsLib__/graphics/orbits/orbit_aquilo.png",
-- 	size = 2240,
-- }
-- data.raw["space-location"]["solar-system-edge"].orbit.sprite = {
-- 	type = "sprite",
-- 	filename = "__PlanetsLib__/graphics/orbits/orbit_solar-system-edge.png",
-- 	size = 3200,
-- }
